# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.9.1";
  ovhVersion = "v0.0.3";
  ddnsVersion = "v0.0.0-20241025234131-7c818ab3fc34";
  vendorHash = "sha256-LO7Uk5sVaTh2NEduEllc0yeprghkt73lnfvkhNdptTs=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.9.1";
    hash = "sha256-28ahonJ0qeynoqf02gws0LstaL4E08dywSJ8s3tgEDI=";
  };
}
